### ISSUE TITLE
Restart server for custom dictionary update

### ISSUE THREAD

**Issue by W1zzardTPU** [meyayl/docker-languagetool#23]
Any suggestions on the best approach to restart the server to apply an update to the user dictionary?

HUP doesn't work in LT to trigger a reload, does it?

**Comment by meyayl** [comment]
I have no idea. LT runs in Java JVM, so whatever applies for Java should apply here as well.

**Comment by W1zzardTPU** [comment]
> The running process is what keeps the container alive

That's exactly the problem and I was wondering if you had any ideas, because I'm assuming you're running your own image in production :) And wrapping it with some startup script that just restarts Java will result in a short service outage, too.

Maybe something could be done with SO_REUSEPORT, but that's probably for LT upstream, at this point maybe just implement some reload functionality in the code

**Comment by meyayl** [comment]
I don't worry about container restarts, it take marely seconds to restart the container. I only use the Chrome browser extension, which to my surprise stores its user dictionary are part of the browser extension inside the browser.

I prefer my main applications in a container to run as PID1. This image uses `tini` to override the exit code of LT, which is the default Java exit code 15 for SIGTERM (+ 128 because it's running in a container). Whenever LT implements a signal handler for SIGTERM, `tini` will be removed right away.

I am not looking forward to implementing this in my image. I am afraid you will have to adapt the sources to your needs and maintain your own custom image.

**Comment by W1zzardTPU** [comment]
The way I implemented this is:

- Add health checks to the pod for Kubernetes
- Create a task in Tekton that uses kubectl to restart the deployment
- Triggered by a webhook in Tekton
- Webhook is called by our site engine when the dictionary file is updated
