### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Zarpyk** [meyayl/docker-languagetool#27]
There are some environment parameters to set user and pass to access, or currently it needs to be public?

**Comment by meyayl** [comment]
As far as I know the open source version of LT does not come with built-in authentication, even though some cli argument might seem like it does. 

I could make the Chrome browser plugin work with a reverse proxy that requires basic auth.  The plugin would not accept an URL like this `http://user:pass@ip:8010/v2`.  

I know that some people use reverse proxies and add paths to obscure how LT is accessed, but I am not a friend of security through obscurity. That's why my instance is not exposed to the internet.

Note: some plugins require https connections, e.g. the Word plugin. The Chrome plugin works perfectly fine with http.

I do not recommend exposing LT to the internet.

**Comment by Zarpyk** [comment]
Thanks for the idea of basic auth, I needed it for an Obsidian.md plugin, so I simply made a PR adding basic auth support.
