### ISSUE TITLE
Default UserName and ApiKey

### ISSUE THREAD

**Issue by ivandrofly** [meyayl/docker-languagetool#30]
Hello there,

I'm trying to access the endpoint `/Words` (http://localhost:8010/v2/words) but it's asking for authentication,
according to https://languagetool.org/http-api/swagger-ui/#/ it requires both **apiKey** and **username**

How do you configure them?

**Comment by meyayl** [comment]
This image uses the official release of the LanguageTool Open Source version. I am not sure how much sense it makes to expect all endpoints of the api from commercial online version to be implemented in the Open Source version as well. For instance, while the commercial version support authentication, the Open Source version does not.

I have no idea whether the `/v2/words` endpoint is supposed to be available in the Open Source version.

Since this question is rather about the application itself, and not the mechanics of the image, I would suggest asking in the official LanguageTool Github project.

**Comment by ivandrofly** [comment]
> This image uses the official release of the LanguageTool Open Source version. I am not sure how much sense it makes to expect all endpoints of the api from commercial online version to be implemented in the Open Source version as well. For instance, while the commercial version support authentication, the Open Source version does not.
> 
> I have no idea whether the `/v2/words` endpoint is supposed to be available in the Open Source version.
> 
> Since this question is rather about the application itself, and not the mechanics of the image, I would suggest asking in the official LanguageTool Github project.

Thanks for info :)
