### ISSUE TITLE
Deployment in eks cluster in kubernetes

### ISSUE THREAD

**Issue by UTSAV-44** [meyayl/docker-languagetool#36]
I am deploying a this image in kubernetes .It is downloading only 3grams and if i want to hit the api it is giving errors as
Error: Internal Error: java.lang.RuntimeException: Expected at least '1grams', '2grams', and '3grams' sub directories but only got [3grams] in /language_model/ngrams/en, detected: en-US.

**Comment by meyayl** [comment]
I am not sure how this should be possible.

The entrypoint script does this:
- Download ngram zips from https://languagetool.org/download/ngram-data/ to ${langtool_languageModel} directory, if the ngrams for the particular language do not already exist.
- Extract downloaded zips, which create the language subfolder with the 3 ngrams folders inside.

Since the zip files of the ngrams didn't change with 23.11.2020, and always extracted the structure mentioned above.

**Comment by meyayl** [comment]
I am closing this issue due to lack of updates.

**Comment by rriemann** [comment]
Dear @UTSAV-44 ,

Did you make it work in kubernetes? Could you possibly share your manifest files?
