### ISSUE TITLE
Optional volumes stay empty

### ISSUE THREAD

**Issue by BaumiCoder** [meyayl/docker-languagetool#42]
I recognize that the directories for the volumes `ngrams` and `fasttext` persist empty. I use the YML file of current state of the repository and only activate ngrams for two languages.
```yml
download_ngrams_for_langs: en,de
```
I would have expected, that the directories get some content with such a default config, because the default config include the volumes. Am I wrong here? The reason of the volumes to cache some language specific stuff, isn't it?

**Comment by meyayl** [comment]
Sorry for responding late.

The volumes are for storing the ngrams language models and the fasttext model.

The environment variable `langtool_languageModel` must be set, otherwise no files will be downloaded.
The container logs should have shown "WARNING: No base path for ngram language modules provided.".

**Comment by BaumiCoder** [comment]
## ngrams
Thanks for your help. There was realy such a warning in my log. Removing the `#` in this line of the yml helps:
https://github.com/meyayl/docker-languagetool/blob/2c93e970377e9fb347beb2a431a738c6561096a7/docker-compose.yml#L24
It seems strange to me that is line is a comment, but not the one for the volumn:
https://github.com/meyayl/docker-languagetool/blob/2c93e970377e9fb347beb2a431a738c6561096a7/docker-compose.yml#L46
Furthermore the default value of the variable should be already `/ngrams` as stated [in the README](https://github.com/meyayl/docker-languagetool?tab=readme-ov-file#parameters). Which does not seems to be true.

Thus the default behaviour is creating the directory `./ngrams` on the host, but without using it, also `download_ngrams_for_langs` is set. I am not sure what is the best behaviour. I see two options:
1. Both lines are a comment and the explination for `download_ngrams_for_langs` explines that both lines have to be uncomment to use ngrams.
2. The default value for `langtool_languageModel` is set to `/ngrams` as stated in the README.

## fasttext
There is a similar relationship between the `fasttext` volumn and the variable `langtool_fasttextModel`, isn't it? If the variable stays empty the volumn is not used, right? 

But the container seems to work fine without fasttext models on the host (i.e. the automatic detection of the language works). Or how can I check if fasttext works correctly?

**Comment by meyayl** [comment]
I owerhauled the entrypoint script of the image. I am not entirely sure why /ngrams was not the default value inherited by the Dockerfile for `langtool_languageModel` , but it is now (again?). The same is true for `langtool_languageModel`.

If needed fasttext can now be disabled by setting `DISABLE_FASTTEXT` to `true`.

Thank you for motivating me to finally do the overhaul I had in mind since quite a while now.

**Comment by meyayl** [comment]
Can the issue be closed?

**Comment by BaumiCoder** [comment]
Now, I checked out the latest version of the image. The files for ngrams and fasttext are now downloaded into the volumes as expected.
