### ISSUE TITLE
Using docker image on a home server and an extern apache proxy

### ISSUE THREAD

**Issue by togme** [meyayl/docker-languagetool#43]
Hello,
I am using your image on a local docker host with external port 8050 and routed via an apache proxy.
configured:
languaguagetool.<ownfqdn>.de 

apache proxy server for languagetool:
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ....
        RewriteEngine on

        ProxyPass / http://192.168.1.10:8050/
        ProxyPassReverse / http://192.168.1.10:8050/
        ProxyPreserveHost On
        ProxyPassReverseCookieDomain 192.168.1.10 languagetool.<domain>.de

        Header always set Access-Control-Allow-Origin "*"
        Header always set Access-Control-Max-Age "1000"
        Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

        SSLCertificateFile /etc/letsencrypt/live/languagetool.<domain>.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/languagetool.<domain>.de/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

I always get the error that the server is not available in firefox. Chrome works!

I read that I have to configure --allow-origin "*" but I don't know where?
dockges yaml looks like:
services:
  languagetool:
    image: meyay/languagetool:latest
    container_name: languagetool
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_CHOWN
    security_opt:
      - no-new-privileges
    ports:
      #- 8010:8010
      - 8050:8010
    environment:
      download_ngrams_for_langs: en,de
      langtool_languageModel: /ngrams
      langtool_fasttextModel: /fasttext/lid.176.bin
      # tut so auch nicht mehr JAVA_OPTS: allow-origin "*"
    volumes:
      - /mnt/docker/languagetool/ngrams:/ngrams
      - /mnt/docker/languagetool/fasttext:/fasttext
volumes:
  languagetool:
    external: true

I'm stuck: what have I to do?

Sincerely Thomas

**Comment by DrFrankensteinUK** [comment]
Hey, I have a slightly different setup but proxying my config via Nginx Proxy Manager for local SSL I added the following environment variables to the config

```services:
  languagetool:
    image: meyay/languagetool:latest
    hostname: languagetool
    container_name: languagetool
    environment:
      download_ngrams_for_langs: en
      langtool_languageModel: /ngrams
      langtool_fasttextModel: /fasttext/lid.176.bin
      MAP_UID: 1031
      MAP_GID: 65536
      DOMAIN: languagetool.mydomain.me
      VIRTUAL_HOST: languagetool.mydomain.me
      VIRTUAL_PORT: 8010
      LETSENCRYPT_HOST: languagetool.mydomain.me
    volumes:
      - /volume2/docker/languagetool/ngrams:/ngrams
      - /volume2/docker/languagetool/fasttext:/fasttext
    ports:
      - 8010:8010
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped```

But as I write this reply I can't remember where I found to use these additional variables... I will see if I can find where I got them!!

**Comment by togme** [comment]
Hello,
I added these vars to my environment - but it still doesn' t work with my firefox plugin (only the original cloudserver of languagetool works):
---
services:
  languagetool:
    image: meyay/languagetool:latest
    container_name: languagetool
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_CHOWN
    security_opt:
      - no-new-privileges
    ports:
      #- 8010:8010
      - 8050:8010
    #security_opt:
    #- no-new-privileges: true
    environment:
      download_ngrams_for_langs: en,de
      langtool_languageModel: /ngrams
      langtool_fasttextModel: /fasttext/lid.176.bin
      DOMAIN: languagetool.mydomain.tld
      VIRTUAL_HOST: languagetool.mydomain.tld
      VIRTUAL_PORT: 8050
      LETSENCRYPT_HOST: languagetool.mydomain.tld
    volumes:
      - /mnt/docker/languagetool/ngrams:/ngrams
      - /mnt/docker/languagetool/fasttext:/fasttext
volumes:
  languagetool:
    external: true

I only see an error that the communiction to my server languagetool.mydomain.tld/v2/check does not work - but I don't see anything in on e of my logs - am I looking wrong?

Thomas

**Comment by DrFrankensteinUK** [comment]
It looks like I may have had these in my compose from another project and upon removal my instance continues to function. So apologies those additional variables should not be required.

**Comment by togme** [comment]
No problem :-)
Does anyone have a proposal?

**Comment by aleeraser** [comment]
I don't use Apache proxy, but I have it working correctly behind Nginx Reverse Proxy, therefore you probably have an issue along the line with your reverse proxy.
My Dockerfile is the same as yours (apart that I commented out the port, as I use the container name directly).

I can therefore open a URL like the following (with Firefox, or `curl`) and I see the correct response: `https://languagetool.mydomain.comv2/check?text=here%20is%20a%20simpe%20test&language=en-US`.

To use my backend with the Firefox extensions as well, I had to enter the URL as `https://languagetool.mydomain.com/v2` (i.e. I had to add the `v2` path), otherwise it would not work.

**Comment by meyayl** [comment]
Sorry for joining late into the conversation. 

Most languagetool extensions require the self-hosted server to be reachable via https.  In order to achieve this, indeed a reverse proxy must be put in front of the container. The rp needs to take care of tls termination, as a container created from this image does not support https by itself - and is never going to.

It has been ages since I used apache as a reverse proxy, and a couple of years since I used a plain nginx server as reverse proxy. Years ago, I would have known the answer by heart. But since a couple of years I either use Traefik or K8s ingress objects, and I am not going to re-learn something that I won't use myself. 

This issue is a non-issue of the image, and providing reverse proxy configurations is out of scope for me. If volunteers want to contribute them as wiki articles, be my guest :)

Thus said, let me respond to some parts:

>I read that I have to configure --allow-origin "" but I don't know where?
There is no configuration option for it, it is hard-wired to [`--allow-origin "*"`](https://github.com/meyayl/docker-languagetool/blob/main/entrypoint.sh#L207), which should work regardless whether the container is reached by a published port or through a reverse proxy.

>VIRTUAL_HOST: languagetool.mydomain.tld
>VIRTUAL_PORT: 8050
This is nothing the image supports. I assume you are running `nginx-proxy/nginx-proxy`, which makes use of the additional environment variables. 

I can highly recommend [Traefik](https://doc.traefik.io/traefik/) as reverse proxy for plain Docker containers and Docker Swarm service tasks.

>To use my backend with the Firefox extensions as well, I had to enter the URL as https://languagetool.mydomain.com/v2 (i.e. I had to add the v2 path), otherwise it would not work.

The `/v2` part is always required.  It's part of the endpoint path - not just for Firefox.  Thank you for making me aware, that I forgot to include the usage description from the Docker Hub repo in the README.md.
