### ISSUE TITLE
Error if volumes 'ngrams' and 'fasttext' are not set

### ISSUE THREAD

**Issue by desk7** [meyayl/docker-languagetool#46]
Before the last update, I had been running the docker container smoothly without using fasttext and ngrams.
After the last update, I had to set those 2 volumes to make the container run without stopping.

Would be possible to use the docker image without setting the aforementioned volumes?

**Comment by meyayl** [comment]
If you feel it makes sense to run it without, it should work as long as you don't specify a read-only file system.

I would neither advice, nor use it without mounting at least the ngrams volume.

**Comment by meyayl** [comment]
Indeed, at the moment there is no way to run the image without volumes. I never thought someone would actually would want to use the image without ngrams. Its definitly a use case I did not test at all - not even with the previous images.

Its caused by two things: now a default path is used for `langtool_languageModel` environment variable is set, and the folder permissions are checked, so that people using volumes actually are informed if there is a missmatch between the folder owner and the used user id in the process.

Let's see if I can come up with something. Though, It might take a while.
