### ISSUE TITLE
Build multi-arch

### ISSUE THREAD

**Issue by sbonnick** [meyayl/docker-languagetool#9]
Hi, I was trying out your image since compared to others, it auto handles the download of models. However, I noticed you are currently only building for AMD64 (X86-64).  Personally I am looking to run this on a ARM.  When you have a few cycles, mind adding support to build for ARM too? 

If it helps, here is some instructions on how to do multi-arch builds using github actions:
https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

**Comment by meyayl** [comment]
Hi sbonnick! 
In the beginning I looked at other LanguageTool images, and remember seeing that they used arm specific fixes. That's why I decided against creating a multi-arch build. I don't feel comfortable maintaining something that I am not able to test myself. I hope you can understand.

If someone is willing to claim ownership for maintaining the image for other architectures, I gladly accept PR's.
